### ISSUE TITLE
Add Maggie Portfolio

### ISSUE THREAD

**Issue by AMTuttle02** [AMTuttle02/HomeTeamCreativity#139]
Add a page for Maggie's Graphic Design Portfolio

**Comment by AMTuttle02** [comment]
Currently, only implementation is a link on the About page. Is there something else you would like with this issue? @mtuttle03

**Comment by mtuttle03** [comment]
No, that's good, I think if I put more, it would become too much

**Comment by mtuttle03** [comment]
could you center the link to portfolio under the image, it's ok if it takes too much work for that, looks great how it is!

**Comment by AMTuttle02** [comment]
@mtuttle03 Updated, please verify and close if complete.
