### ISSUE TITLE
Update Homepage Front End Design

### ISSUE THREAD

**Issue by mtuttle03** [AMTuttle02/HomeTeamCreativity#181]
I sent you new designs for the homepage, we will probably have to video to let me explain, but I don't like the homepage, and it's the first thing customers see so it needs updated. Not any time soon, just adding it to the list. I not sure how complex it will be on back end :) 

Note: Implement Tailwind has been combined with this issue.

**Comment by AMTuttle02** [comment]
Combined with improve customization item.
