### ISSUE TITLE
3x T-Shirts

### ISSUE THREAD

**Issue by mtuttle03** [AMTuttle02/HomeTeamCreativity#190]
Bug found, not sure if we can fix it. The t-shirts are offered in 3x, so as a customer, if I choose 3x t-shirt, then switch the style to crewneck, long sleeve, or hoodie, I cannot change the size, it just glitches when I click any other size. Could you redirect the size selection to 2x when the style is switched maybe? Sorry, I know it would be easier if the others were offered in 3x but they aren't :( Thanks!!

**Comment by mtuttle03** [comment]
Priority: 1

**Comment by AMTuttle02** [comment]
I will reset the size option to none when switching to a different style so the user knows 3x is not available and do not accidentally order 2x.

**Comment by mtuttle03** [comment]
Ok thanks!

**Comment by mtuttle03** [comment]
Bug found in Custom Design shirt only, all other shirt designs are good for 3x sizing, but the custom design lets me order a 3x long sleeve, crewneck and hoodie, but should be empty sizing on those styles. I tried to attach screenshot here, idk if it worked though

![Image](https://github.com/AMTuttle02/HomeTeamCreativity/assets/149885763/e1e30d78-f00f-4023-a233-47ffea9bbe78)

**Comment by AMTuttle02** [comment]
In test branch. Not on test.hometeamcreativity.com yet
