### ISSUE TITLE
Add code implementation for discount codes

### ISSUE THREAD

**Issue by mtuttle03** [AMTuttle02/HomeTeamCreativity#200]
Add an option box for me to checkmark if sales tax should be excluded for the customer, and not charge them sales tax. Or add code like you said somehow.

add option for adding discount codes to products for sitewide discounts to be advertised. Allow code to be customized for percent off and name.
Priority: 2 if this is what we doing for sales tax exempts, if not, priority: 3

**Comment by mtuttle03** [comment]
add option for adding discount codes to products for sitewide discounts to be advertised. Allow code to be customized for percent off and name.
Priority: 2 if this is what we doing for sales tax exempts, if not, priority: 3

**Comment by AMTuttle02** [comment]
Coupon code create & update complete.
Remaining Task: Allow users to enter coupons when ordering.

**Comment by AMTuttle02** [comment]
Display done for entering coupons. Logic & pulling backend data is still required.

**Comment by AMTuttle02** [comment]
Logic complete on checkout page for discount

**Comment by AMTuttle02** [comment]
Logic complete on stripe page. Can use total session variable for order confirmation email total.

**Comment by mtuttle03** [comment]
WOWWWW, this so cool!! I can do promos and stuff now!! Ahh so good, but I get stuck when I try to Create Coupon see @AMTuttle02 


![Image](https://github.com/user-attachments/assets/99d03ed3-6e39-470b-ba56-6179a1e61276)

**Comment by mtuttle03** [comment]
WOOO

**Comment by AMTuttle02** [comment]
Add categories when creating coupons

**Comment by mtuttle03** [comment]
Good job!!
