### ISSUE TITLE
Remove Copy below Additional Request Details when ordering a product: "This may increase the price..."

### ISSUE THREAD

**Issue by mtuttle03** [AMTuttle02/HomeTeamCreativity#233]
Remove this from the product ordering page, since majority of customizations will be with back designs, and I include back design price when I upload front and back, even if they don't get anything on the back. 

![Image](https://github.com/user-attachments/assets/779e0517-4d2d-49a1-b9c9-e3b8c4ca5712)

**Comment by AMTuttle02** [comment]
Removed
