### ISSUE TITLE
T-Shirt Uploads

### ISSUE THREAD

**Issue by mtuttle03** [AMTuttle02/HomeTeamCreativity#234]

**Comment by mtuttle03** [comment]
I upload a T-Shirt as shown: 


![Image](https://github.com/user-attachments/assets/74f3fd89-c2aa-4a1c-b016-d1147a434b82)

Then, I click on the shirt as if I would order it and this pops up:


![Image](https://github.com/user-attachments/assets/f907169e-bee5-4bac-b1c9-0fa61d31b242)


I go to Edit product, everything looks right, not sure why it do this now. :( 



![Image](https://github.com/user-attachments/assets/7893b317-80e3-4dc0-8345-efa12bb1c463)

**Comment by AMTuttle02** [comment]
Please test in prod or test. Uploaded both since deemed a bug in prod
