### ISSUE TITLE
Allow same item to be ordered with different customization

### ISSUE THREAD

**Issue by mtuttle03** [AMTuttle02/HomeTeamCreativity#242]

**Comment by mtuttle03** [comment]
Christy gave feedback, and maybe we can fix this somehow. So, for the things that are required to be customized (tumblers, etc) customers can only order 1 of the design with one name. I know it does what it is supposed to and how we have it makes sense, but you can't order the same product, same design, just with different customization. It makes sense, and I want to keep it on for everything else if possible, but I think people probably should be able to order the same product, same design, with different customizations. If they want the same name customization, they can just increase quantity, but maybe we can change it for a different name/customization to be able to be ordered. Thanks so much

**Comment by AMTuttle02** [comment]
Remove Click [Here](https://hometeamcreativity.com/customOrder) To Order a Custom Design

**Comment by mtuttle03** [comment]
Good job !!! :)
