### ISSUE TITLE
Allow designs on Backs

### ISSUE THREAD

**Issue by AMTuttle02** [AMTuttle02/HomeTeamCreativity#97]
Allow users to put designs on the back.

Note: Products table in db updated.

~~Update Upload page to cross check file input and default selection.~~

Pages To Update (.jsx):
~~Cart~~
~~CheckoutComplete~~
~~Order~~
~~Dashboard~~
~~CustomOrder~~
~~EditProducts~~
~~HomeContents~~
~~Products~~
~~SearchResults~~
~~Upload~~
~~UploadSuccess~~

**Comment by AMTuttle02** [comment]
High priority

**Comment by AMTuttle02** [comment]
Priority: 1

**Comment by mtuttle03** [comment]
Bug: Long Sleeve upload preview showed me the wrong image, I uploaded an image of 2024 with dates, it showed me the previous upload I did. Then, the image did not show at all on the shirt, and I can't seem to find the front design I uploaded. Attached screenshot 

![Image](https://github.com/AMTuttle02/HomeTeamCreativity/assets/149885763/a68161fa-63a9-4c33-96b8-66617c7f50c2)



![Image](https://github.com/AMTuttle02/HomeTeamCreativity/assets/149885763/7b818b02-0f08-4ee9-b476-e9214c3a6480)

**Comment by mtuttle03** [comment]
this is what I was trying to upload ^^

back:

![Image](https://github.com/AMTuttle02/HomeTeamCreativity/assets/149885763/9c93da5f-4361-46c7-859b-3f6ded20ecac)

front:


![Image](https://github.com/AMTuttle02/HomeTeamCreativity/assets/149885763/c8c3d1cd-5f2e-4967-9d77-68a5005f275f)

**Comment by mtuttle03** [comment]
Bug: On any upload of front and back designs, I can't find where I can see the front design, it seems to only be showing me the back design, the default location. :(

**Comment by mtuttle03** [comment]
I have 5 uplods of test designs uploaded to the test site, you can search "test" to see them 

Let me know if I need to do something or if you have a plan to fix. Thank you!!

**Comment by AMTuttle02** [comment]
@mtuttle03 This issue should be fixed. Please try again in test. Be sure to refresh

**Comment by mtuttle03** [comment]
@AMTuttle02  When I place an order for the shirt I called test front and back, I like how in the dashboard, I click the shirt to enlarge it and when I hover over the shirt, it flips back and forth between front and back. Could we have that hover and flip on the actual product page, when I click to enlarge. Hopefully that makes sense. The link is https://test.hometeamcreativity.com/order/186 and it's on the linked page I want it to do what it does on my dashboard, when I enlarge and if flips between front and back design. Thanks

**Comment by mtuttle03** [comment]
and it's not on My Admin Dashboard, the dashboard I referring to is the one called "Order Details" when the orderComplete is in the URL

**Comment by AMTuttle02** [comment]
Continuous arrow button

**Comment by AMTuttle02** [comment]
@mtuttle03 Changes should be implemented in test. Please review
